import { SupportedLanguage } from '../types/intelligence';

export type CapabilityStatus = 'SUPPORTED' | 'PARTIAL' | 'UNSUPPORTED';

export interface LanguageCapabilityProfile {
  language: SupportedLanguage;
  parser: CapabilityStatus;
  symbolExtraction: CapabilityStatus;
  importAnalysis: CapabilityStatus;
  callAnalysis: CapabilityStatus;
  typeAnalysis: CapabilityStatus;
  flowAnalysis: CapabilityStatus;
  securityRules: CapabilityStatus;
  sourceMapping: CapabilityStatus;
}

export const LANGUAGE_CAPABILITIES: Record<SupportedLanguage, LanguageCapabilityProfile> = {
  TYPESCRIPT: {
    language: 'TYPESCRIPT',
    parser: 'SUPPORTED',
    symbolExtraction: 'SUPPORTED',
    importAnalysis: 'SUPPORTED',
    callAnalysis: 'SUPPORTED',
    typeAnalysis: 'SUPPORTED',
    flowAnalysis: 'SUPPORTED',
    securityRules: 'SUPPORTED',
    sourceMapping: 'SUPPORTED',
  },
  JAVASCRIPT: {
    language: 'JAVASCRIPT',
    parser: 'SUPPORTED',
    symbolExtraction: 'SUPPORTED',
    importAnalysis: 'SUPPORTED',
    callAnalysis: 'SUPPORTED',
    typeAnalysis: 'PARTIAL',
    flowAnalysis: 'SUPPORTED',
    securityRules: 'SUPPORTED',
    sourceMapping: 'SUPPORTED',
  },
  PYTHON: {
    language: 'PYTHON',
    parser: 'SUPPORTED',
    symbolExtraction: 'SUPPORTED',
    importAnalysis: 'SUPPORTED',
    callAnalysis: 'SUPPORTED',
    typeAnalysis: 'PARTIAL',
    flowAnalysis: 'SUPPORTED',
    securityRules: 'SUPPORTED',
    sourceMapping: 'SUPPORTED',
  },
  GO: {
    language: 'GO',
    parser: 'PARTIAL',
    symbolExtraction: 'PARTIAL',
    importAnalysis: 'PARTIAL',
    callAnalysis: 'PARTIAL',
    typeAnalysis: 'PARTIAL',
    flowAnalysis: 'PARTIAL',
    securityRules: 'PARTIAL',
    sourceMapping: 'SUPPORTED',
  },
  RUST: {
    language: 'RUST',
    parser: 'PARTIAL',
    symbolExtraction: 'PARTIAL',
    importAnalysis: 'PARTIAL',
    callAnalysis: 'PARTIAL',
    typeAnalysis: 'PARTIAL',
    flowAnalysis: 'PARTIAL',
    securityRules: 'PARTIAL',
    sourceMapping: 'SUPPORTED',
  },
  JAVA: {
    language: 'JAVA',
    parser: 'PARTIAL',
    symbolExtraction: 'PARTIAL',
    importAnalysis: 'PARTIAL',
    callAnalysis: 'PARTIAL',
    typeAnalysis: 'PARTIAL',
    flowAnalysis: 'PARTIAL',
    securityRules: 'PARTIAL',
    sourceMapping: 'SUPPORTED',
  },
  CSHARP: {
    language: 'CSHARP',
    parser: 'PARTIAL',
    symbolExtraction: 'PARTIAL',
    importAnalysis: 'PARTIAL',
    callAnalysis: 'PARTIAL',
    typeAnalysis: 'PARTIAL',
    flowAnalysis: 'PARTIAL',
    securityRules: 'PARTIAL',
    sourceMapping: 'SUPPORTED',
  },
  CPP: {
    language: 'CPP',
    parser: 'PARTIAL',
    symbolExtraction: 'PARTIAL',
    importAnalysis: 'PARTIAL',
    callAnalysis: 'UNSUPPORTED',
    typeAnalysis: 'UNSUPPORTED',
    flowAnalysis: 'UNSUPPORTED',
    securityRules: 'UNSUPPORTED',
    sourceMapping: 'SUPPORTED',
  },
  PHP: {
    language: 'PHP',
    parser: 'PARTIAL',
    symbolExtraction: 'PARTIAL',
    importAnalysis: 'PARTIAL',
    callAnalysis: 'PARTIAL',
    typeAnalysis: 'UNSUPPORTED',
    flowAnalysis: 'PARTIAL',
    securityRules: 'PARTIAL',
    sourceMapping: 'SUPPORTED',
  },
  RUBY: {
    language: 'RUBY',
    parser: 'PARTIAL',
    symbolExtraction: 'PARTIAL',
    importAnalysis: 'PARTIAL',
    callAnalysis: 'PARTIAL',
    typeAnalysis: 'UNSUPPORTED',
    flowAnalysis: 'PARTIAL',
    securityRules: 'PARTIAL',
    sourceMapping: 'SUPPORTED',
  },
  KOTLIN: {
    language: 'KOTLIN',
    parser: 'PARTIAL',
    symbolExtraction: 'PARTIAL',
    importAnalysis: 'PARTIAL',
    callAnalysis: 'PARTIAL',
    typeAnalysis: 'PARTIAL',
    flowAnalysis: 'PARTIAL',
    securityRules: 'PARTIAL',
    sourceMapping: 'SUPPORTED',
  },
  SWIFT: {
    language: 'SWIFT',
    parser: 'PARTIAL',
    symbolExtraction: 'PARTIAL',
    importAnalysis: 'PARTIAL',
    callAnalysis: 'PARTIAL',
    typeAnalysis: 'PARTIAL',
    flowAnalysis: 'PARTIAL',
    securityRules: 'PARTIAL',
    sourceMapping: 'SUPPORTED',
  },
  SQL: {
    language: 'SQL',
    parser: 'SUPPORTED',
    symbolExtraction: 'PARTIAL',
    importAnalysis: 'UNSUPPORTED',
    callAnalysis: 'UNSUPPORTED',
    typeAnalysis: 'UNSUPPORTED',
    flowAnalysis: 'UNSUPPORTED',
    securityRules: 'SUPPORTED',
    sourceMapping: 'SUPPORTED',
  },
  SHELL: {
    language: 'SHELL',
    parser: 'PARTIAL',
    symbolExtraction: 'PARTIAL',
    importAnalysis: 'UNSUPPORTED',
    callAnalysis: 'PARTIAL',
    typeAnalysis: 'UNSUPPORTED',
    flowAnalysis: 'UNSUPPORTED',
    securityRules: 'PARTIAL',
    sourceMapping: 'SUPPORTED',
  },
  TERRAFORM: {
    language: 'TERRAFORM',
    parser: 'PARTIAL',
    symbolExtraction: 'PARTIAL',
    importAnalysis: 'UNSUPPORTED',
    callAnalysis: 'UNSUPPORTED',
    typeAnalysis: 'UNSUPPORTED',
    flowAnalysis: 'UNSUPPORTED',
    securityRules: 'UNSUPPORTED',
    sourceMapping: 'SUPPORTED',
  },
  DOCKERFILE: {
    language: 'DOCKERFILE',
    parser: 'SUPPORTED',
    symbolExtraction: 'UNSUPPORTED',
    importAnalysis: 'UNSUPPORTED',
    callAnalysis: 'UNSUPPORTED',
    typeAnalysis: 'UNSUPPORTED',
    flowAnalysis: 'UNSUPPORTED',
    securityRules: 'PARTIAL',
    sourceMapping: 'SUPPORTED',
  },
  JSON: {
    language: 'JSON',
    parser: 'SUPPORTED',
    symbolExtraction: 'UNSUPPORTED',
    importAnalysis: 'UNSUPPORTED',
    callAnalysis: 'UNSUPPORTED',
    typeAnalysis: 'UNSUPPORTED',
    flowAnalysis: 'UNSUPPORTED',
    securityRules: 'UNSUPPORTED',
    sourceMapping: 'SUPPORTED',
  },
  YAML: {
    language: 'YAML',
    parser: 'SUPPORTED',
    symbolExtraction: 'UNSUPPORTED',
    importAnalysis: 'UNSUPPORTED',
    callAnalysis: 'UNSUPPORTED',
    typeAnalysis: 'UNSUPPORTED',
    flowAnalysis: 'UNSUPPORTED',
    securityRules: 'PARTIAL',
    sourceMapping: 'SUPPORTED',
  },
  TOML: {
    language: 'TOML',
    parser: 'SUPPORTED',
    symbolExtraction: 'UNSUPPORTED',
    importAnalysis: 'UNSUPPORTED',
    callAnalysis: 'UNSUPPORTED',
    typeAnalysis: 'UNSUPPORTED',
    flowAnalysis: 'UNSUPPORTED',
    securityRules: 'UNSUPPORTED',
    sourceMapping: 'SUPPORTED',
  },
  MARKDOWN: {
    language: 'MARKDOWN',
    parser: 'SUPPORTED',
    symbolExtraction: 'UNSUPPORTED',
    importAnalysis: 'UNSUPPORTED',
    callAnalysis: 'UNSUPPORTED',
    typeAnalysis: 'UNSUPPORTED',
    flowAnalysis: 'UNSUPPORTED',
    securityRules: 'UNSUPPORTED',
    sourceMapping: 'SUPPORTED',
  },
  UNSUPPORTED_LANGUAGE: {
    language: 'UNSUPPORTED_LANGUAGE',
    parser: 'UNSUPPORTED',
    symbolExtraction: 'UNSUPPORTED',
    importAnalysis: 'UNSUPPORTED',
    callAnalysis: 'UNSUPPORTED',
    typeAnalysis: 'UNSUPPORTED',
    flowAnalysis: 'UNSUPPORTED',
    securityRules: 'UNSUPPORTED',
    sourceMapping: 'PARTIAL',
  },
};

export function getLanguageCapability(language: SupportedLanguage): LanguageCapabilityProfile {
  return LANGUAGE_CAPABILITIES[language] || LANGUAGE_CAPABILITIES.UNSUPPORTED_LANGUAGE;
}
